import Head from "next/head";
import Nav from "../components/Nav";
import Results from "../components/Results";
import SideNav from "../components/SideNav";
import requests from "../utils/requests";

export default function Home({ request, popularMovies, top_ratedMovies }) {
  return (
    <div>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/movie.ico" />
      </Head>
      <div className="flex flex-row h-screen ">
        <SideNav />

        <Results
          results={request}
          popular={popularMovies}
          top={top_ratedMovies}
        />
        <Nav />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const [popularMoviesRes, top_ratedMoviesRes, requestRes] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3${
        requests[genre]?.url || requests.fetchTrending.url
      }`
    ),
  ]);
  const [popularMovies, top_ratedMovies, request] = await Promise.all([
    popularMoviesRes.json(),
    top_ratedMoviesRes.json(),
    requestRes.json(),
  ]);

  return {
    props: {
      popularMovies: popularMovies.results,
      top_ratedMovies: top_ratedMovies.results,
      request: request.results,
    },
  };
}
